### ISSUE TITLE
Milestone 1 Review 

### ISSUE THREAD

**Issue by Jonathon22** [nss-evening-cohort-13/renaissance-fair-dashboard-renaissance-fair-dashboard#29]
- [x] Pull down code 
- [x] run it locally 
- [x] create bug tickets
- [x] place bug tickets in the milestone
- [x] deploy to firebase
