### ISSUE TITLE
Milestone 3 Review

### ISSUE THREAD

**Issue by esrduke95** [nss-evening-cohort-13/renaissance-fair-dashboard-renaissance-fair-dashboard#33]
- [x]  Pull down code
- [x]  run it locally
- [x]  create bug tickets
- [x]  place bug tickets in the milestone
- [x]  deploy to firebase
